############################################################
#
# Home Assistant Configuration
#
############################################################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude 
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/London
  customize: !include customise.yaml

http:
  #base_url: !secret base_url
  api_password: !secret api_password
  #ssl_certificate: /config/SSL/fullchain.pem
  #ssl_key: /config/SSL/privkey.pem
  # server_host: 
  trusted_networks:
    - 10.0.0.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3
  cors_allowed_origins:
  - https://google.com
  - https://home-assistant.io
  - https://api.ai
  use_x_forwarded_for: True
  
config:
logger:
  default: warn
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: info
    homeassistant.components.automation: debug
    homeassistant.components.light: info
    homeassistant.components.sensor: info
    homeassistant.components.scene: info
    homeassistant.components.switch: info
history:
recorder:
  purge_days: 7
discovery:
sun:
conversation:
logbook:
frontend:

emulated_hue:
  host_ip: 10.0.0.5
  expose_by_default: false

# Components

media_player:
  - platform: plex
    host: 10.0.0.20
    port: 32400
    entity_namespace: 'plex'
    scan_interval: 5
    show_all_controls: truw
    use_custom_entity_ids: true
    use_episode_art: true
  - platform: cast
  - platform: samsungtv
    host: 10.1.2.33
    port: 8001
    name: Living Room TV
    scan_interval: 60
    mac: BC:14:85:A3:E4:26

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_pass
  client_id: home-assistant-mqtt
  keepalive: 60

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

light:
  - platform: hue
    host: 10.0.0.3
    allow_unreachable: true
    allow_in_emulated_hue: false
    
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

panel_iframe:
  router:
    title: 'Router'
    icon: mdi:router-wireless
    url: 'http://10.0.0.1'

device_tracker:
  - platform: netgear
    host: 10.0.0.1
    username: !secret router_user
    password: !secret router_password
    interval_seconds: 30
    consider_home: 180
    track_new_devices: false
    exclude:
     - 192.168.1.12
     - 192.168.1.18
     - 192.168.1.10
     - 192.168.1.20
     - 192.168.1.2
     - 192.168.1.5
     - 192.168.1.9
     - 192.168.1.8
     - 192.168.1.3
     - 192.168.1.66
     - 192.168.1.19
     
ios:
    
# Includes

group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
camera: !include cameras.yaml
switch: !include switches.yaml
input_select: !include input_selects.yaml
input_slider: !include input_sliders.yaml