############################################################
#
# Home Assistant Sensors Configuration
#
############################################################

# MetOffice
sensor:
  - platform: metoffice
    api_key: !secret met_api
    monitored_conditions:
      - weather
      - temperature
      - feels_like_temperature
      - wind_speed
      - wind_direction
      - wind_gust
      - visibility
      - uv
      - precipitation
      - humidity

# Arlo Sensor
sensor:
  - platform: arlo
    name: Arlo
    monitored_conditions:
      - captured_today
      - last_capture
      - total_cameras

# Plex Activity
sensor:    
  - platform: plex
    name: Plex
    username: !secret plex_server_username
    password: !secret plex_server_password
    server: NASNG
